# -*- coding: utf-8 -*-
"""invoice-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/HemakshiKumar/1f89a3f7cb0a5260acd33b25c8734280/invoice-generator.ipynb
"""

print("MENU")
print("S.no.".ljust(12), "Item".ljust(12), "Cost".ljust(12))
menu = {1:["Pizza", 100],
        2:["Noodles", 130],
        3:["Burger", 150],
        4:["Pasta",120],
        5:["Coffee", 100],
        6:["Salad", 90],
        7:["Popcorn", 120],
        8:["Tomato Soup", 130],
        9:["Icecream", 100],
        10:["Garlic Bread", 150]}
for key, value in menu.items():
    print(str(key).ljust(12),str(value[0]).ljust(12), str(value[1]).ljust(12))

#variables

bill = {}
p = 0
a = 0
b = 0
c = 0
p1 = 0
cnt=11
print("Enter respective serial numbers to get each item;\nEnter hash (#) when you are done.")
while True:
  inp = input("Item to be added to bucket: ")
  if inp == "#":
    break
  n = int(input("Quantity of item: "))
  a = menu[int(inp)]
  b = a[1]
  c = a[0]
  p = n*b+p
  p1 = n*b
  #cnt= serial number; c = item; n=qty; p1=price per item
  bill[cnt] = [c, n, p1]
  cnt = cnt+1
print("************************************************")
print()
print()
print("BILL")
name = input("Name: ")
date = input("Date: ")
print("________________________________________________")
print("S.No".ljust(12), "Snack".ljust(12), "Qty".ljust(12), "Price".ljust(12), sep= " ")
print("________________________________________________")
for key, value in bill.items():
    print(str(key).ljust(12),str(value[0]).ljust(12), str(value[1]).ljust(12), str(value[1]).ljust(12))
print("Your total price is", "rs.", p)
#confirmation
print("Do you want to make changes in your bill?")
conf = int(input("Type 1 for yes; 2 for no: "))
if conf == 1:
    l=1
    m=0
    print("Type the following letters to run the desired command:\nA: Add an item\nB: Deleting an item\nC: Modify an item\nD: Display menu\nE: Done/Exit")
    while l==1:
      x = input("Command to run: ")
      x = x.capitalize()
      #adding to bill
      if x == "A":
        bill2={}
        inp2= input("S.no. of item to be added (from menu): ")
        n2 = int(input("Quantity of item: "))
        a = menu[int(inp2)]
        b = a[1]
        c = a[0]
        p = n2*b+p
        p1 = n*b
        #cnt= serial number; c = item; n2=qty; p1=price per item
        bill2[cnt]= [c, n2, p1]
        bill.update(bill2)
        for key, value in bill.items():
           bill[key]=value
        cnt+=1
        print("Item added!")
      #deleting from bill
      elif x == "B":
        bill2 = bill.items()
        bill2 = sorted(bill2)
        print("************************************************")
        print()
        print("Name:", name)
        print("Date:", date)
        print("________________________________________________")
        print("S.No".ljust(12), "Snack".ljust(12), "Qty".ljust(12), "Price".ljust(12), sep= " ")
        print("________________________________________________")
        for i in bill2:
           print(str(i[0]).ljust(12), str(i[1][0].ljust(12)), str(i[1][1]).ljust(12), str(i[1][2]).ljust(12))
        n2 = int(input("S.no. of item to be deleted (from bill): "))
        m = bill[n2]
        p = p - m[2]
        del bill[n2]
        bill2={}
        cnt = 1
        for key in bill:
           bill2[cnt]= bill[key]
           cnt=cnt+1
        bill = bill2
        print("Item deleted!")
      #modifying bill
      elif x == "C":
        bill2 = bill.items()
        bill2 = sorted(bill2)
        print("************************************************")
        print()
        print("Name:", name)
        print("Date:", date)
        print("________________________________________________")
        print("S.No".ljust(12), "Snack".ljust(12), "Qty".ljust(12), "Price".ljust(12), sep= " ")
        print("________________________________________________")
        for i in bill2:
           print(str(i[0]).ljust(12), str(i[1][0].ljust(12)), str(i[1][1]).ljust(12), str(i[1][2]).ljust(12))
        inp2 = int(input("S.no. of item to modify (from bill): "))
        n2 = int(input("New quantity of the item: "))
        p1 = int((bill[inp2][2]/bill[inp2][1])*n2)
        a = bill[inp2][0]
        del bill[inp2]
        bill[inp2]=[a,n2,p1]
        p = 0
        for i in bill:
          p = p+bill[i][2]
        print("Item modified!")
      #to display menu
      elif x == "D":
        print("MENU")
        print("S.no.".ljust(12), "Item".ljust(12), "Cost".ljust(12))
        for key, value in menu.items():
            print(str(key).ljust(12),str(value[0]).ljust(12), str(value[1]).ljust(12))
      #ending the while loop
      elif x == "E":
         l = 0
      else:
        print("Invalid command, try again")
      print("Your total price is", "rs.", p)
elif conf == 2:
   pass
done()
print("************************************************")
print("Thank you for your purchase!")

def done():
        l=0
        bill2 = bill.items()
        bill2 = sorted(bill2)
        print("************************************************")
        print()
        print("FINAL BILL")
        print("Name:", name)
        print("Date:", date)
        print("________________________________________________")
        print("S.No".ljust(12), "Snack".ljust(12), "Qty".ljust(12), "Price".ljust(12), sep= " ")
        print("________________________________________________")
        for i in bill2:
           print(str(i[0]).ljust(12), str(i[1][0].ljust(12)), str(i[1][1]).ljust(12), str(i[1][2]).ljust(12))